/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as LocationRouteImport } from './routes/location'
import { Route as BookRouteImport } from './routes/book'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesPremiumBeardRouteImport } from './routes/services.premium-beard'
import { Route as ServicesHaircutBeardRouteImport } from './routes/services.haircut-beard'
import { Route as ServicesFatherSonRouteImport } from './routes/services.father-son'
import { Route as ServicesExecutiveCutRouteImport } from './routes/services.executive-cut'
import { Route as ServicesClassicCutRouteImport } from './routes/services.classic-cut'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesPremiumBeardRoute = ServicesPremiumBeardRouteImport.update({
  id: '/premium-beard',
  path: '/premium-beard',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesHaircutBeardRoute = ServicesHaircutBeardRouteImport.update({
  id: '/haircut-beard',
  path: '/haircut-beard',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesFatherSonRoute = ServicesFatherSonRouteImport.update({
  id: '/father-son',
  path: '/father-son',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesExecutiveCutRoute = ServicesExecutiveCutRouteImport.update({
  id: '/executive-cut',
  path: '/executive-cut',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesClassicCutRoute = ServicesClassicCutRouteImport.update({
  id: '/classic-cut',
  path: '/classic-cut',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/location': typeof LocationRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/classic-cut': typeof ServicesClassicCutRoute
  '/services/executive-cut': typeof ServicesExecutiveCutRoute
  '/services/father-son': typeof ServicesFatherSonRoute
  '/services/haircut-beard': typeof ServicesHaircutBeardRoute
  '/services/premium-beard': typeof ServicesPremiumBeardRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/location': typeof LocationRoute
  '/reviews': typeof ReviewsRoute
  '/services/classic-cut': typeof ServicesClassicCutRoute
  '/services/executive-cut': typeof ServicesExecutiveCutRoute
  '/services/father-son': typeof ServicesFatherSonRoute
  '/services/haircut-beard': typeof ServicesHaircutBeardRoute
  '/services/premium-beard': typeof ServicesPremiumBeardRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/location': typeof LocationRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/classic-cut': typeof ServicesClassicCutRoute
  '/services/executive-cut': typeof ServicesExecutiveCutRoute
  '/services/father-son': typeof ServicesFatherSonRoute
  '/services/haircut-beard': typeof ServicesHaircutBeardRoute
  '/services/premium-beard': typeof ServicesPremiumBeardRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/location'
    | '/reviews'
    | '/services'
    | '/services/classic-cut'
    | '/services/executive-cut'
    | '/services/father-son'
    | '/services/haircut-beard'
    | '/services/premium-beard'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/location'
    | '/reviews'
    | '/services/classic-cut'
    | '/services/executive-cut'
    | '/services/father-son'
    | '/services/haircut-beard'
    | '/services/premium-beard'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/location'
    | '/reviews'
    | '/services'
    | '/services/classic-cut'
    | '/services/executive-cut'
    | '/services/father-son'
    | '/services/haircut-beard'
    | '/services/premium-beard'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  LocationRoute: typeof LocationRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/premium-beard': {
      id: '/services/premium-beard'
      path: '/premium-beard'
      fullPath: '/services/premium-beard'
      preLoaderRoute: typeof ServicesPremiumBeardRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/haircut-beard': {
      id: '/services/haircut-beard'
      path: '/haircut-beard'
      fullPath: '/services/haircut-beard'
      preLoaderRoute: typeof ServicesHaircutBeardRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/father-son': {
      id: '/services/father-son'
      path: '/father-son'
      fullPath: '/services/father-son'
      preLoaderRoute: typeof ServicesFatherSonRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/executive-cut': {
      id: '/services/executive-cut'
      path: '/executive-cut'
      fullPath: '/services/executive-cut'
      preLoaderRoute: typeof ServicesExecutiveCutRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/classic-cut': {
      id: '/services/classic-cut'
      path: '/classic-cut'
      fullPath: '/services/classic-cut'
      preLoaderRoute: typeof ServicesClassicCutRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesClassicCutRoute: typeof ServicesClassicCutRoute
  ServicesExecutiveCutRoute: typeof ServicesExecutiveCutRoute
  ServicesFatherSonRoute: typeof ServicesFatherSonRoute
  ServicesHaircutBeardRoute: typeof ServicesHaircutBeardRoute
  ServicesPremiumBeardRoute: typeof ServicesPremiumBeardRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesClassicCutRoute: ServicesClassicCutRoute,
  ServicesExecutiveCutRoute: ServicesExecutiveCutRoute,
  ServicesFatherSonRoute: ServicesFatherSonRoute,
  ServicesHaircutBeardRoute: ServicesHaircutBeardRoute,
  ServicesPremiumBeardRoute: ServicesPremiumBeardRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  LocationRoute: LocationRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
